# Generated by Django 4.0.5 on 2022-06-25 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=2024)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'новая'), ('published', 'опубликовано'), ('reject', 'отклонено')], default='new', max_length=48)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
