# Generated by Django 4.0.5 on 2022-06-25 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announce',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('published', 'опубликовано'), ('reject', 'отклонено')], default='new', max_length=48),
        ),
        migrations.AlterField(
            model_name='announce',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
