# Generated by Django 4.0.5 on 2022-06-25 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_announce_author_announce_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announce', to=settings.AUTH_USER_MODEL),
        ),
    ]
